pipeline {
    agent any 
    tools {
      // Install the Maven version configured as "M3" and add it to the path.
      maven "mymaven"
   }
    stages {
        stage('Clone') {
            steps {
                echo "checking out the repo"
                git 'https://github.com/AbdulItsMe/jenkins-demo.git'
            
            }
        }
        stage('Build') {
         steps {
            dir('MavenProject') {
                sh "mvn clean install findbugs:findbugs test javancss:report"
            }
            // Run Maven on a Unix agent.
         }
      }
        
        stage('Archieve Artifacts'){
            steps {
                echo "archiving the artifacts"
                archiveArtifacts 'MavenProject/multi3/target/*.war'
            }
            
        }
        stage('Deployment') {
            // Deployment
            steps {
                script {
                    echo "deployment"
                          copyArtifacts fingerprintArtifacts: true, projectName: 'Module 10', selector: lastSuccessful(), target: '/var/lib/jenkins/tomcat'
                }
            }
        }
        stage('publish html report') {
            steps{
                echo "publishing the html report"
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: '', reportFiles: 'index.html', reportName: 'HTML Report', reportTitles: ''])
            }
        }
        stage('clean up') {
            steps {
                echo "cleaning up the workspace"
                cleanWs()
            }
        }
        stage("Metrics"){
            steps{
            parallel ( "JavaNcss Report":   
            {
              node('slave'){
                git 'https://github.com/AbdulItsMe/jenkins-demo.git'
                sh "cd javancss-master ; mvn test javancss:report ; pwd"
                  }
            },
            "FindBugs Report" : {
            node('slave'){
                sh "mkdir javancss1 ; cd javancss1 ;pwd"
                git 'https://github.com/AbdulItsMe/jenkins-demo.git'
                sh "cd javancss-master ; mvn findbugs:findbugs ; pwd"
                deleteDir()
                }

              }
         )
            }
         post{
                success {
                    emailext body: 'Successfully completed pipeline project with archiving the artifacts', subject: 'Pipeline was successfull', to: 'a.abdulrahman41@gmail.com'
                }
    }
}
        
    }
}
