pipeline {
    agent any 
    tools {
      // Install the Maven version configured as "M3" and add it to the path.
      maven "mymaven"
   }
    stages {
        stage('Clone') {
            steps {
                echo "checking out the repo"
                git 'https://github.com/AbdulItsMe/jenkins-demo.git'
            
            }
        }
        stage('Build') {
         steps {
            dir('MavenProject') {
                sh "mvn clean install findbugs:findbugs test javancss:report"
            }
            // Run Maven on a Unix agent.
         }
      }
        
        stage('Archieve Artifacts'){
            steps {
                echo "archiving the artifacts"
                archiveArtifacts 'MavenProject/multi3/target/*.war'
            }
            
        }
        
        
        stage("Metrics"){
            steps{
            parallel ( "Cobertura Report":   
            {
              node('slave'){
                git 'https://github.com/AbdulItsMe/jenkins-demo.git'
                sh "cd MavenProject ; mvn test cobertura:cobertura -Pmetrics ; pwd"
                cobertura autoUpdateHealth: false, autoUpdateStability: false, coberturaReportFile: 'MavenProject/multi1/target/site/cobertura/coverage.xml', conditionalCoverageTargets: '70, 0, 0', failUnhealthy: false, failUnstable: false, lineCoverageTargets: '80, 0, 0', maxNumberOfBuilds: 0, methodCoverageTargets: '80, 0, 0', onlyStable: false, sourceEncoding: 'ASCII', zoomCoverageChart: false
                  }
            },
            "FindBugs Report" : {
            node('slave'){
                sh "mkdir javancss1 ; cd javancss1 ;pwd"
                git 'https://github.com/AbdulItsMe/jenkins-demo.git'
                sh "cd MavenProject ; mvn findbugs:findbugs ; pwd"
                findbugs canComputeNew: false, defaultEncoding: '', excludePattern: '', healthy: '', includePattern: '', isRankActivated: true, pattern: 'MavenProject/multi1/target/findbugsXml.xml', unHealthy: ''    
                deleteDir()
                }

              }
            )
            }
        }
        stage('Deployment') {
            // Deployment
            steps {
                script {
                    echo "deployment"
                          copyArtifacts fingerprintArtifacts: true, projectName: 'Module 10', selector: lastSuccessful(), target: '/var/lib/jenkins/tomcat'
                }
            }
        }
        
        stage('Email') {
        steps {
            emailext body: '$DEFAULT_CONTENT', subject: '$DEFAULT_SUBJECT', to: '$receipent'
            }
        }
        stage('publish html report') {
            steps{
                echo "publishing the html report"
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: '', reportFiles: 'index.html', reportName: 'HTML Report', reportTitles: ''])
            }
        }
        stage('clean up') {
            steps {
                echo "cleaning up the workspace"
                cleanWs()
            }
        }
    }
}
